### ISSUE TITLE
Call to Action Form

### ISSUE THREAD

**Issue by mateoclarke** [txappleseed/txappleseedmap#26]
Creating a popup form on top of the map that essentially gives the visitor action items:
- contact school rep.
- contact TexasAppleseed
- take other course of action etc.

**Comment by mlsintx** [comment]
I think this is some @codecofee19  was going to work on?

**Comment by codecofee19** [comment]
Yes I'm still working on it. I'm close to finishing thankfully

**Comment by codecofee19** [comment]
Okay done!
