### ISSUE TITLE
School District Search Bar 

### ISSUE THREAD

**Issue by mateoclarke** [txappleseed/txappleseedmap#27]
Having a search bar to locate a particular school district

**Comment by mlsintx** [comment]
That is something I could probably add.  I was under the impression at some point that someone else was going to add, but they have gone away.

**Comment by mateoclarke** [comment]
Awesome, can you assign this Issue to yourself @mlsintx via "Assignees" on the right sidebar?

**Comment by mlsintx** [comment]
done :)

**Comment by mateoclarke** [comment]
Update:

@mlsintx is has something close to working locally and will be pushing to `develop`. She mentioned she needs help getting the polygon to highlight once you zoom. I can help with that once the code is up.

**Comment by mlsintx** [comment]
If anyone interested in this could look at the develop branch I think we can close this one.

**Comment by mscarey** [comment]
belated thanks @mlsintx
