### ISSUE TITLE
New Data Available?

### ISSUE THREAD

**Issue by mateoclarke** [txappleseed/txappleseedmap#29]
> Another issue is that this project is now so old that there's another year of data available. If we want, I can do the analysis over with the new data. I've learned a lot since last time, so it should be easier now.
> @mscarey

**Comment by mscarey** [comment]
I've now updated our data from 2014 to 2015. The TEA hasn't posted 2016 yet, but the TEA has shared it with Appleseed in a different format. That means I could update the map to 2016, but it would take more work.

**Comment by mscarey** [comment]
Even though we have some 2015-16 discipline data in the file called Statewide15-16.csv, I don't think we should use it because the Special Ed category is missing, and that category is very important to Appleseed. So I vote for sticking to the 2014-15 data.

**Comment by mlsintx** [comment]
Hey Mateo,

I did get the district file simplified and smaller.  I got those population values from TX demo 2014 added to the geojson and was going to put it up here, but now I see this information about newer data but sticking with the 2014 data and I'm not sure I have everything matching.  TX demo populations were used to calculate DistrictDisparities2014?

**Comment by mscarey** [comment]
The files that end in 2015 are OK to use (and newer). I was just saying we shouldn't try to make 2016 files.

**Comment by mateoclarke** [comment]
Think we're good on this issue now... 🎉
