### ISSUE TITLE
Feedback from 11/16 Call with Morgan

### ISSUE THREAD

**Issue by mateoclarke** [txappleseed/txappleseedmap#44]
Changes we discussed for the maps:

- [x] 1. City names darker if possible

- [x] 2. instead of "no data" use "Data not available for this student group."

- [x] 3. in rollover text change to: ___% of ______ ISD's 10957 students are classified as _____. _____ students received out-of-school suspensions ____ times, accounting for ___ % of all out-of-school suspensions.

**Comment by mlsintx** [comment]
There are some basemap tiling schemes that will display reference (like city names) as an overlay, but I'm not sure Stamen has any.  I can look at that shortly.  I have a branch I want to upload so you can look at it?  I don't want to overwrite the master so could you pull it down to look at it?  I need to run get kids to bed but I will pull a branch(?) in an hour or so?  The version I made has data fixed in the corner as you scroll over the districts and I have the search bar up but I haven't got it to work so I gutted all that for now.  The outline comes with a much more sophisticated autocomplete scheme for search (from Twitter?)  One I have used in the past is more simple so I may get that working tomorrow

**Comment by mateoclarke** [comment]
There is a conversation on the slack about how we don't have the necessary data to say how many students received each suspension.

"_____ students received out-of-school suspensions ____ times"

We do have the number of actual punished students (not incidents) for the special ed and economic disadvantage groups, but not for the race groups. Matt would rather not incorporate punished-student counts in the map since he doesn't see how to make them work for the race groups.

"...accounting for ___ % of all out-of-school suspensions."

This requires don't some math to come up with the percent. I'll have to come back to it.

cc/ @MCraven2800

**Comment by mateoclarke** [comment]
newest popup message structure from Morgan...

**African American** students received out-of-school suspensions **number (total count by group)** times, accounting for **X**% of all out-of-school suspensions.

Still requires a new calculation of the percent I believe, but it is doable.

**Comment by mlsintx** [comment]
I have been trying to add control to your map, not very successfully.  I
tried to make a commit but i am getting an error about no upstream.  I am
too tired to look at this any more tonight.  Will try again in the morning.

**Comment by mateoclarke** [comment]
hmm, not sure what that means. 

Which repo are you trying to push your branch to?

if you do `git remote -v` what is origin? Are you pushing to that?

**Comment by mlsintx** [comment]
Mateo, I had 'checked out' a neIw branch locally that wasn't remote, so I
guess that is what messed me up.  I retrieved all the new work you did last
night and have worked some more on this.  The problem, I think is having
everything in that map object?  I wasn't sure where to put the function
(for the click event, or really hover event) where the map object is
defined.  I think I I might have figured out something just now.  I placed
a million console log messages all over the code to see where
this.mapObject is defined.  If you want to look at my version right now I
could try again.  Maybe you can see what I'm trying to do and tell me how
to fix it?  I just have a place holder for the control until I get the
event handler coming up right.

**Comment by mateoclarke** [comment]
Yeah, the code around understanding the `mapObject` is pretty confusing and messy but throwing in `console.log`s or `debugger`s is totally the right thing to do to try to understand what is happening and what causes what.

I'd be happy to review your code and make suggestions.

Can you push the local branch you are working to a branch I can see on Github?
I think the error you may have seen that you described as no upstream may just be that you need to run a different command the first time you push a local branch to a remote repo.
http://stackoverflow.com/questions/6089294/why-do-i-need-to-do-set-upstream-all-the-time

Would you try push your branch to this repo again, or your own fork, and share the link with me? 

Just don't merge anything in master right now. I want to keep it stable at least through tonight and start to be more mindful about merging into master.

**Comment by mlsintx** [comment]
It's up there mls_nov_13

**Comment by mateoclarke** [comment]
https://github.com/txappleseed/txappleseedmap/pull/48
