### ISSUE TITLE
No data color

### ISSUE THREAD

**Issue by mateoclarke** [txappleseed/txappleseedmap#53]
There was a concern from Yamanda that the gray #ebeaea (which represents No Data) is too close to #f2f0f7 (which is the 5th color in our 10 color scale going from purple to red). Maybe we could replace the gray with a white. What do y’all think?

![](https://dsh.re/9d92e)

**Comment by mateoclarke** [comment]
I created a PR, but the team is leaning towards @mlsintx's idea of trying a hatching or pinstripe pattern.

https://github.com/teastman/Leaflet.pattern

**Comment by mscarey** [comment]
Updating on this as we're revising the map. The current dev branch of the map (in @rebfrank's repo) has some white regions, some gray regions, and some striped regions. The white region is supposed to be where no notable disparity is detected. I think gray is supposed to indicate erroneous data and stripes are supposed to indicate no data, but the difference isn't currently explained in the popup text for each district, and I think it would be more understandable if we used stripes for both, with no gray.

**Comment by mscarey** [comment]
I made the gray (error) color darker, so I think it's distinguishable now. And @mlsintx added hatching for missing data a long time ago.
