### ISSUE TITLE
Clean up data directory

### ISSUE THREAD

**Issue by mateoclarke** [txappleseed/txappleseedmap#57]
From @mscarey on Slack: 
> There's a lot of stuff in the data directory. I'm sure some of it is obsolete, and it's hard for me to know which files actually need to be documented. Is DistrictPercentage2015.csv the source for all the data that's actually in use in the map? I produced some files after that: the ones that came from the "StudentSums2016.ipynb" file on December 12. (Morgan asked for them in an email.) Did any of the December 12 files also get incorporated in the map? There's new data available from the state for 2016, so I could do an update that matches the format of DistrictPercentage2015.csv if that works for everybody.

**Comment by mscarey** [comment]
#68 is supposed to address this.

**Comment by mlsintx** [comment]
I'm sure this will need to happen again, but Matt has cleaned up the data.
